lib/pages/dashboard_page.dart, lib/services/nt4.dart, lib/services/nt4_connection.dart, lib/services/shuffleboard_nt_listener.dart, lib/widgets/dashboard_grid.dart, lib/widgets/network_tree/tree_row.dart, test/pages/dashboard_page_test.dart, test/services/shuffleboard_nt_listener_test.dart
Allow the WPILib shuffleboard API to:
- Create tabs
- Add widgets to tabs
- Select tabs
=> Shuffleboard API Integration

elasticlib/Elastic.java, lib/pages/dashboard_page.dart, lib/services/robot_notifications_listener.dart
Also rename the notification table from "elastic" to "Elastic", and add more safety checks when parsing notification data
=> Increase notification time

lib/pages/dashboard_page.dart, lib/services/hotkey_manager.dart, test/pages/dashboard_page_test.dart
Adds shortcuts for Ctrl + Tab and Ctrl + Shift + Tab to navigate tabs left and right
=> Tab left+right navigation shortcuts

lib/widgets/nt_widgets/single_topic/number_bar.dart, lib/widgets/nt_widgets/single_topic/number_slider.dart, lib/widgets/nt_widgets/single_topic/radial_gauge.dart, lib/widgets/nt_widgets/single_topic/voltage_view.dart, test/widgets/nt_widgets/single-topic/number_bar_test.dart, test/widgets/nt_widgets/single-topic/number_slider_test.dart, test/widgets/nt_widgets/single-topic/radial_gauge_test.dart
=> Fixed number views not working with integers

lib/widgets/mjpeg.dart, lib/widgets/nt_widgets/multi-topic/camera_stream.dart, pubspec.yaml
Also cancel bandwidth timers when a camera stream is removed
=> Update version to 2025.0.0-beta-3

lib/widgets/dialog_widgets/dialog_text_input.dart
Fixed NT search widget only updating when you click enter, now it updates on change.
=> Make NT search textfield update on change

lib/services/nt_connection.dart, lib/widgets/network_tree/networktables_tree.dart, test/widgets/network_tree/networktables_tree_test.dart
Should allow them to still integrate properly into the tree
=> Add a fix for NT topics without a leading /

lib/pages/dashboard_page.dart, lib/widgets/dialog_widgets/dialog_text_input.dart
Fixes an issue where all text fields would submit after editing by adding an option to auto submit when editing
=> Fix continuous text submission

lib/pages/dashboard_page.dart, lib/services/elastic_layout_downloader.dart, lib/widgets/tab_grid.dart, test/pages/dashboard_page_test.dart, test/services/elastic_layout_downloader_test.dart, test/test_util.dart
- Add menu to select which file to download from the robot
- Write unit tests
=> Improvements to Remote Layout Downloading

lib/pages/dashboard_page.dart, lib/services/field_images.dart, lib/services/settings.dart, lib/widgets/dialog_widgets/layout_drag_tile.dart, lib/widgets/draggable_containers/models/list_layout_model.dart, lib/widgets/editable_tab_bar.dart, lib/widgets/network_tree/networktables_tree.dart, lib/widgets/nt_widgets/multi-topic/field_widget.dart, lib/widgets/pixel_ratio_override.dart, lib/widgets/settings_dialog.dart, lib/widgets/tab_grid.dart, test/widgets/pixel_ratio_override_test.dart, test/widgets/settings_dialog_test.dart
Ability to change the effective DPI of the grid to compensate for device scaling, has not had significant testing so it will remain experimental for the time being
=> Experimental: Change the DPI of the grid

lib/widgets/mjpeg.dart
Streams are now much faster and properly process frames split between packets
=> Fix Camera Stream Speed

lib/widgets/nt_widgets/multi-topic/gyro.dart
The entire widget scales proportionally to fit the widget size
=> Fix gyro widget scaling

lib/main.dart, lib/pages/dashboard_page.dart, lib/services/app_distributor.dart, lib/widgets/custom_appbar.dart, lib/widgets/editable_tab_bar.dart, lib/widgets/settings_dialog.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, test/pages/dashboard_page_test.dart, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
- Dynamically hide title if window is too small
- Shrink menu bar buttons
- Move update icon into tab bar
Resolves #195 and #196
=> Shrink Minimum Size & Fix Calculations

lib/widgets/nt_widgets/single_topic/text_display.dart
=> Fix text cursor position jumping while typing

lib/services/nt_widget_builder.dart, lib/widgets/nt_widgets/nt_widget.dart, lib/widgets/nt_widgets/single_topic/large_text_display.dart, test/widgets/nt_widgets/single-topic/boolean_box_test.dart, test/widgets/nt_widgets/single-topic/graph_test.dart, test/widgets/nt_widgets/single-topic/large_text_display_test.dart, test/widgets/nt_widgets/single-topic/match_time_test.dart, test/widgets/nt_widgets/single-topic/multi_color_view_test.dart, test/widgets/nt_widgets/single-topic/number_bar_test.dart, test/widgets/nt_widgets/single-topic/number_slider_test.dart, test/widgets/nt_widgets/single-topic/radial_gauge_test.dart, test/widgets/nt_widgets/single-topic/single_color_view_test.dart, test/widgets/nt_widgets/single-topic/toggle_button_test.dart, test/widgets/nt_widgets/single-topic/toggle_switch_test.dart, test/widgets/nt_widgets/single-topic/voltage_view_test.dart
=> Add large text widget

lib/pages/dashboard_page.dart, lib/widgets/dialog_widgets/layout_drag_tile.dart, lib/widgets/editable_tab_bar.dart, lib/widgets/network_tree/networktables_tree.dart, lib/widgets/tab_grid.dart
- Switching tabs while dragging no longer breaks everything
- Reorganized (and improved) add widget dialog
=> Add Widget Dialog Fixes

lib/pages/dashboard_page.dart, pubspec.lock, pubspec.yaml
Resolves #221
The issue is in the elegant_notification package, a PR for the fix has been opened [here](https://github.com/koukibadr/Elegant-Notification/pull/144)
Once the PR is merged I'll update the package version, but for now I'm having the dependency be downloaded from my fork of the package.
=> Fix robot notifications appearing off-screen

lib/widgets/nt_widgets/multi-topic/network_alerts.dart
=> Always show scrollbar for alerts widget

lib/widgets/tab_grid.dart
Fixes this happening when resizing up or left
=> Fix resize preview snapping to opposite direction

lib/main.dart, lib/pages/dashboard_page.dart, lib/widgets/custom_appbar.dart, lib/widgets/settings_dialog.dart
MacOS decides to use a different font size
=> Fix App Bar Sizing on MacOS

lib/widgets/tab_grid.dart
Improves performance and fixes camera streams resetting when a widget is removed
=> Fix entire widget tree rebuilding when widget is removed

lib/widgets/mjpeg.dart, lib/widgets/nt_widgets/multi-topic/camera_stream.dart, test/widgets/mjpeg_test.dart
=> Cycle Through Multiple Camera Streams

lib/services/nt4_client.dart, pubspec.lock, pubspec.yaml
Should guarantee that NT will reconnect no matter what
=> Use periodic timer for auto reconnection

lib/services/nt4_client.dart, lib/services/nt_connection.dart, lib/widgets/nt_widgets/multi-topic/combo_box_chooser.dart, lib/widgets/nt_widgets/multi-topic/split_button_chooser.dart, test/test_util.dart, test/widgets/nt_widgets/multi-topic/combo_box_chooser_test.dart, test/widgets/nt_widgets/multi-topic/split_button_chooser_test.dart
- Publishes retained topic for selected
- Reuses more reliable logic from Glass
- Cache all values, and only update when non-null
- Use only one listener for the string chooser state changes
=> Improve string chooser reliability

.github/workflows/elastic-ci.yml, installer_setup_script.iss
- Add uninstall icon
- Update CI to use manual install and CLI
=> Innosetup Fixes

lib/widgets/nt_widgets/single_topic/graph.dart
- Disconnecting and reconnecting properly resets everything
- Improved logic for updating series controller
=> Fix graph visual bugs and errors

elasticlib/Elastic.java, elasticlib/elasticlib.py
=> [ElasticLib] Move NotificationLevel into Elastic class scope
