Gold872/elastic-dashboard

lib/widgets/mjpeg.dart
lib/widgets/nt_widgets/multi-topic/camera_stream.dart

For every camera stream widget, instead of having a separate http request and stream each time it is rendered, it uses data from the same stream. This also allows for auto disposal/closing whenever the widget becomes invisible, and the actual camera stream widget doesn't need to be cached, only the state has to be.

Improved camera stream efficiency

---

lib/widgets/network_tree/networktables_tree_row.dart

If you drag a table containing a widget that doesn't have a widget implementation, it will never unsubscribe
This has the widget model be unsubscribed and disposed before returning null in the tree row's `toWidgetContainerModel()` method

Fix widgets not unsubscribing if type doesn't have a widget implementation

---

lib/pages/dashboard_page.dart
lib/services/nt4_client.dart

When adding a topic announce listener, the listener method is called with all previously announced topics.

Fix field objects not rendering if connection is already established during widget creation

---

elasticlib/Elastic.java
lib/pages/dashboard_page.dart
lib/services/nt4_client.dart
lib/services/nt_connection.dart
lib/services/robot_alerts.dart
lib/services/robot_notifications_listener.dart
pubspec.lock
pubspec.yaml
test/pages/dashboard_page_test.dart
test/services/shuffleboard_nt_listener_test.dart
test/test_util.dart

https://github.com/Gold872/elastic-dashboard/assets/68785503/6e22f1bb-cafc-4cf4-82bd-e77da0f40d26
Robot code usage: 
```java
@Override
public void autonomousInit() {
Elastic.sendAlert(AlertLevel.INFO, "Autonomous!", "The robot is now in auto.");
```
There are 3 levels of notifications:
INFO: 
WARNING: 
ERROR:
The idea is that the driver can get a notification when something happens (eg. an arm extends too far and gets disabled). 
Users can copy the Elastic class into their robot project, and use those methods to push notifications to the dashboard.

Allow robot created notifications

---

lib/widgets/draggable_containers/draggable_widget_container.dart
lib/widgets/draggable_containers/models/list_layout_model.dart
lib/widgets/draggable_containers/models/widget_container_model.dart
lib/widgets/tab_grid.dart

Fix grid size not working

---

elasticlib/Elastic.java
lib/services/nt4_client.dart
lib/services/nt_connection.dart
lib/services/robot_notifications_listener.dart
test/pages/dashboard_page_test.dart
test/services/robot_notifications_listener_test.dart
test/test_util.dart

The first notification data received will only be ignored if the message is from more than 3 seconds in the past

Fix first notification not showing

---

lib/pages/dashboard_page.dart
lib/widgets/dialog_widgets/dialog_text_input.dart
lib/widgets/network_tree/networktables_tree.dart
test/pages/dashboard_page_test.dart

Wasnt sure how to write the test for this, if you (the reviewer) will be able to explain me / do it ill be glad

Added a search query option for the addwidget dialog

---

lib/widgets/nt_widgets/multi-topic/command_widget.dart

If the command button is pressed too frequently, it can get stuck in the "running" state

Fix command widget lockup

---

lib/services/struct_schemas/pose2d_struct.dart
lib/services/struct_schemas/swerve_module_state_struct.dart
pubspec.lock
test/services/struct_schemas/pose2d_struct_test.dart
test/services/struct_schemas/swerve_module_state_struct_test.dart

Resolves #91
Not currently used by any widgets but will allow for Field2d and Swerve widget to use WPILib structs with the sendable rewrite

Added struct decoding for pose2d and swerve module state

---

lib/services/nt_widget_builder.dart

Closes #89 
Allows for easier addition of new widget types and better readability over adding manually to each of the maps

Widget registrar

---

lib/widgets/nt_widgets/multi-topic/camera_stream.dart

After disconnecting from network tables, if no image was received from a camera stream, there would be an error due to trying to display an image from an empty cache. This is a fix for it.

Fix camera stream edge case error when no image is received 

---

.github/workflows/elastic-ci.yml

On some versions on linux the app will not open since it gets built on the latest version of ubuntu. Linux build will now always be built on Ubuntu 22.04.

Fix Linux compatibility

---

lib/pages/dashboard_page.dart
test/pages/dashboard_page_test.dart
test/services/shuffleboard_nt_listener_test.dart
test/test_util.dart

Resolves #116 and #118
`Ctrl + ,` will open the settings dialog
`Ctrl + K` will connect to the robot
`Ctrl + Shift + K` will connect to sim

Added shortcuts for robot connection and opening settings

---

elasticlib/Elastic.java
lib/pages/dashboard_page.dart
pubspec.lock

* Added method chaining API
* Allow removing auto dismiss
* Add javadocs

Improve Java ElasticLib

---

.github/workflows/elastic-ci.yml
lib/services/nt_widget_builder.dart
lib/widgets/network_tree/networktables_tree.dart
lib/widgets/network_tree/networktables_tree_row.dart
lib/widgets/tab_grid.dart
test/pages/dashboard_page_test.dart

- Allows sendables with an unknown/unregistered type to be turned into a list layout
- Speeds up creation of list layouts
- Fixes an issue with list layouts not unsubscribing if a drag finishes before list layout is created
Resolves #141

Fix list layout creation for unregistered sendable types

---

lib/services/log.dart
lib/widgets/mjpeg.dart
lib/widgets/nt_widgets/multi-topic/camera_stream.dart
pubspec.lock
pubspec.yaml
test/widgets/nt_widgets/multi-topic/camera_stream_test.dart

Simplified the logic for the mjpeg stream decoding and display, along with adding text for bandwidth and FPS
* Use stream builder instead of flutter hooks
* Remove StreamManager, instead have one change notifier to hold the state and decoding streams
* Only start a camera stream when the widget becomes focused
* Rebuild the widget when focus changes, automatically restarting streams properly

Camera stream optimizations

---

elasticlib/Elastic.java
elasticlib/elasticlib.cpp
elasticlib/elasticlib.h
elasticlib/elasticlib.py

All:
* Rename the Notification class to Alert to match the user-facing function
* Remove the Elastic prefix from class names since the namespace (C++), outer class (Java), or package name (Python) already provides that namespacing
C++:
* Flatten the type structure
* Put all classes and functions in an elastic namespace
* Since the Alert class provides setters and getters, just make the members public to allow [aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization)
* Remove redundant Javadoc tags from comments
* Rewrite the Javadoc-like comments to follow Doxygen conventions
* Make pixel counts use ints, since them being fractional makes no sense
* Move the JSON serialization and NT publishing to a .cpp file
* Use WPILib's bundled fmtlib instead of …

Make elasticlib C++ and Python libraries more idiomatic

---

lib/pages/dashboard_page.dart
lib/services/elastic_layout_downloader.dart
lib/widgets/tab_grid.dart

Depends on https://github.com/wpilibsuite/allwpilib/pull/7527
- Adds the ability to download and merge a layout from a robot via HTTP
- Deprecates the Shuffleboard API support as remote downloading is much more reliable and easier to maintain
Resolves #134

Remote Layout Download from Robot

---

lib/services/nt_widget_builder.dart
lib/widgets/nt_widgets/multi-topic/differential_drive.dart
lib/widgets/nt_widgets/multi-topic/gyro.dart
lib/widgets/nt_widgets/multi-topic/motor_controller.dart
lib/widgets/nt_widgets/nt_widget.dart
lib/widgets/nt_widgets/single_topic/number_bar.dart
lib/widgets/nt_widgets/single_topic/number_slider.dart
lib/widgets/nt_widgets/single_topic/radial_gauge.dart
lib/widgets/nt_widgets/single_topic/voltage_view.dart
pubspec.lock
pubspec.yaml
test/widgets/nt_widgets/multi-topic/differential_drive_test.dart
test/widgets/nt_widgets/multi-topic/gyro_test.dart
test/widgets/nt_widgets/multi-topic/motor_controller_test.dart
test/widgets/nt_widgets/single-topic/number_bar_test.dart
test/widgets/nt_widgets/single-topic/number_slider_test.dart
test/widgets/nt_widgets/single-topic/radial_gauge_test.dart
test/widgets/nt_widgets/single-topic/voltage_view_test.dart

All number bars and sliders now use a different library for the linear gauge. There is very little visible difference, and all slider widgets function the same way.

Switch Gauge Library

---

lib/services/nt4_client.dart
lib/widgets/nt_widgets/single_topic/text_display.dart
test/widgets/nt_widgets/single-topic/text_display_test.dart

- Automatically enable submit button if the topic is persistent
- Show red underline if value has not been published
Resolves #174

Text Display Improvements

---

lib/widgets/tab_grid.dart

When loading a list layout from a json, the enabled state of the widgets wasn't initialized, which was an issue when downloading layouts

Fix initial enabled state for list layouts

---

lib/pages/dashboard_page.dart
lib/widgets/nt_widgets/multi-topic/combo_box_chooser.dart
lib/widgets/nt_widgets/multi-topic/split_button_chooser.dart

When reconnecting the ComboBox Chooser, Split Button Chooser, and a widget dragging in (conditionally) would throw error messages

Fix reconnection error messages

---

lib/services/nt4_client.dart

Previously, if the IP address was changed while network tables was disconnected, there would be a new connection attempt "loop" that tried to connect at the same time as the existing connection attempt "loop(s)". When the connection was eventually established, multiple clients would be created on Network Tables.
Now, when trying to connect, any additional calls to `_connect()` while trying to connect will be blocked off, preventing this issue

Prevent simultaneous connections

---

lib/pages/dashboard_page.dart
lib/services/settings.dart
lib/widgets/nt_widgets/single_topic/text_display.dart
lib/widgets/settings_dialog.dart
test/widgets/nt_widgets/single-topic/text_display_test.dart
test/widgets/settings_dialog_test.dart

- Adds a toggle under Developer that automatically shows submit button. Off by default
addresses #199

Add setting to automatically show submit button

---

lib/pages/dashboard_page.dart

Resolves #233 
Files were being written in UTF16 instead of UTF8, which was causing issues when opening

Export Files using UTF8 instead of UTF16

---

web/index.html

This may be useful in some cases where someone tries loading this in an environment where JavaScript is nonfunctional or if they forgot to enable it.
This is definitely a niche thing, feel free to reject it; this seemed easier than opening an issue.

Add noscript text saying JS is required

---

lib/pages/dashboard_page.dart
lib/services/field_images.dart
lib/widgets/dialog_widgets/layout_drag_tile.dart
lib/widgets/draggable_containers/models/list_layout_model.dart
lib/widgets/draggable_containers/models/nt_widget_container_model.dart
lib/widgets/draggable_containers/models/widget_container_model.dart
lib/widgets/network_tree/networktables_tree.dart
lib/widgets/network_tree/networktables_tree_row.dart
lib/widgets/nt_widgets/multi_topic/camera_stream.dart
lib/widgets/nt_widgets/multi_topic/field_widget.dart
lib/widgets/nt_widgets/multi_topic/pid_controller.dart
lib/widgets/nt_widgets/multi_topic/profiled_pid_controller.dart
lib/widgets/nt_widgets/nt_widget.dart
lib/widgets/tab_grid.dart

Initially, the app did not properly use ChangeNotifier models properly, using them as a way to rebuild stateless widgets rather than representing a state, and these would be automatically disposed while being cached, which would cause many errors to be thrown. Since then, the app's state management has been restructured, making these workarounds obsolete.

Remove forceDispose()
